### ISSUE TITLE
Password expiration with 2FA enabled causes redirect loop and AccessError

### ISSUE THREAD

**Issue by Paulius11** [BacHaSoftware/password_policy#1]
**Hello,**

There’s a bug in the **`bhs_password_policy`** extension that occurs in **Odoo v17** when a user’s password has expired **and two-factor authentication (2FA)** is enabled.

---

## ⚙️ Steps to Reproduce

1. Enable **2FA** in Odoo.  
2. Configure the **bhs_password_policy** module so that a user’s password can expire.  
3. Log in as a user whose password has expired.  
4. The system correctly prompts for 2FA authentication.  
5. After entering the correct 2FA code, the user is simply **redirected** instead of being asked to set a new password.

---

---

## 🧩 Root Cause

When the password expiration logic runs, the method  
`user.action_expire_password()` calls `signup_prepare()` on the related `res.partner` record.  
That method tries to write to the fields:
- `signup_token`  
- `signup_type`  
- `signup_expiration`

These fields are restricted to users in the **“Administration / Access Rights”** group, causing an **AccessError** when executed by a normal user during authentication.

---

## ✅ Expected Behavior

After successful 2FA verification, the user should be redirected to the **password reset** page (to set a new password).

---

## ❌ Actual Behavior

After entering the 2FA code, the system raises an `AccessError` and redirects without allowing the password change.

---

**Comment by trungnq-bhsoft** [comment]
Dear @Paulius11 ,

Thank you for reporting the bug. We appreciate your detailed input, as it is invaluable for our investigation and resolution process.

We are pleased to inform you that the bug has been fixed in the latest commit. To implement the fix, please follow these steps:

1. Download the latest code from our GitHub repository.
2. Overwrite the module source code on your Odoo instance with the newly downloaded files.
3. Go to your Odoo instance and upgrade the module to ensure the changes take effect.

If you have any questions or need further assistance, please don't hesitate to reach out.

**Comment by Paulius11** [comment]
I’ve applied the latest changes from the repository, but the issue still persists.

After successfully completing 2FA verification, the user is redirected back to the login page instead of being prompted to change the expired password.

```
2025-10-27 15:47:39,021 INFO odoo.addons.auth_totp.models.res_users: 2FA check: SUCCESS for res.users...
2025-10-27 15:47:39,023 INFO werkzeug: "POST /web/login/totp HTTP/1.1" 303 -
2025-10-27 15:47:39,544 INFO werkzeug: "GET /web HTTP/1.1" 303 -
2025-10-27 15:47:40,387 INFO werkzeug: "GET /web/login HTTP/1.1" 200 -
```

As shown above, the 2FA check completes successfully, but the system redirects to /web/login instead of the password reset page.

**Comment by trungnq-bhsoft** [comment]
Hello @Paulius11 

Thank you for reaching out and sharing your concerns with us. We appreciate your feedback and the opportunity to assist you.

Our development team has thoroughly investigated the issue you reported and did not encounter the same problem on our end. To ensure that you have the most up-to-date version, please make sure to download the latest codebase from our repository and follow the instructions to upgrade the Odoo module:

1. **Download the latest code** from our GitHub repository.
2. **Overwrite the module source code** on your Odoo instance with the newly downloaded files.
3. **Go to your Odoo instance** and upgrade the module to apply the changes.

<img width="1438" height="993" alt="Image" src="https://github.com/user-attachments/assets/1b9692dc-3295-4804-9ade-d4f405dc7bdd" />

If you continue to experience difficulties after following these steps, please let us know, and we will be more than happy to assist you further.
Ps: If you able to to capture screen recording and add it here, pls do it.
Thank you for your understanding.

**Comment by Paulius11** [comment]
@trungnq-bhsoft

Thanks for the update. After upgrading to the latest version, the initial issue is resolved — the redirection after 2FA now works correctly. However, I’ve encountered a new bug affecting regular users.
When a non-admin user attempts to log in with an expired password, the system throws an AccessError during the signup_prepare() call. This is because the method tries to write to the following fields on res.partner:

- signup_token
- signup_expiration
- signup_type

These fields are restricted to users in the “Administration / Access Rights” group, which causes the write operation to fail for regular users.

```
Access Denied by ACLs for operation: write, uid: 6, model: res.partner, fields: signup_token, signup_expiration, signup_type``
odoo.exceptions.AccessError: The requested operation can not be completed due to security restrictions.
```

I believe the issue is here: https://github.com/BacHaSoftware/password_policy/blob/2b1e691c0cbd4dce89e78d2291eade2225da1f65/bhs_password_policy/models/res_users.py#L247

If I'm correct, this can be resolved by adding sudo() to the signup_prepare() call:

```
user.mapped("partner_id").sudo().signup_prepare(
                signup_type="reset", expiration=expiration
            )
```
Let me know if this makes sense.

**Comment by trungnq-bhsoft** [comment]
Hi @Paulius11 

Thank you for your patience and for bringing the issue to our attention. You were correct in your observation. We identified a logic error that had been fixed internally but had not yet been synchronized to our GitHub repository.

Additionally, we have updated the flow for changing passwords when they expire, particularly for users utilizing two-factor authentication (2FA). This adjustment aligns with the process we implemented for Odoo 18.

**The updated flow is as follows:**
1. Log in with your current password.
2. Enter your 2FA code.
3. Proceed to change your password.
4. Enter 2FA code once again 
Then we  able to continue working with our application

You can review the specific changes in our GitHub commit here: [Commit Details](https://github.com/BacHaSoftware/password_policy/pull/2/commits/b0fd66124ca1fadfb177abeaa382c845d5ce4956).

Please ensure you download the latest codebase and follow the necessary steps to implement these updates. If you have any further questions or need assistance, feel free to reach out.

Thank you for your understanding and support!

**Comment by Paulius11** [comment]
Thanks! It seems to fix the issue!
